### ISSUE TITLE
2.1.3: Missing required argument $restrictions of MageKey\CustomerRestriction\Model\Restriction\Pool

### ISSUE THREAD

**Issue by crankycyclops** [magekey/module-customer-restriction#3]
After upgrading to 2.1.3 via composer, I get the following error in var/log/exception.log:

`main.CRITICAL: Missing required argument $restrictions of MageKey\CustomerRestriction\Model\Restriction\Pool. {"exception":"[object] (BadMethodCallException(code: 0): Missing required argument $restrictions of MageKey\\CustomerRestriction\\Model\\Restriction\\Pool. at /path/to/store/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:222)"} []`

I'm running Magento 2.2.8.

**Comment by magekey** [comment]
@crankycyclops I can't reproduce the issue on 2.2.8. The frontend DI has been moved to the global scope. Please make sure DI is compiled. (setup:di:compile).

**Comment by crankycyclops** [comment]
Hmm, I'll have to dig into this some more. I'm testing in development mode, so the di:compile step shouldn't be necessary, but I'll change it to production and run that step so I can see if it makes a difference. If I find anything more detailed that suggests it might be an issue with the module rather than my own setup, I'll comment again with my findings.

**Comment by wejobes-abt** [comment]
I am getting this issue as well, but during checkout.  I recently upgraded the module while updating to Magento 2.3.1.  This is after doing di:compile  The issue is because the di.xml entry is in the frontend area (the frontend directory).  It should be in the global area (no directory).  I have had this issue before when dealing with things during checkout. If I remember correctly it is because some where going through a webservice request, so it should have been in one of the webservice areas (webapi_rest or webapi_soap) as well.  It is an odd fluke.

By placing a di.xml file of the following contents into just the etc directory should fix this (I am going to test in a few and confirm):

```<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
<type name="MageKey\CustomerRestriction\Model\Restriction\Pool">
        <arguments>
            <argument name="restrictions" xsi:type="array">
                <item name="registration" xsi:type="array">
                    <item name="email" xsi:type="string">MageKey\CustomerRestriction\Model\Restriction\Registration\Email</item>
                </item>
                <item name="login" xsi:type="array">
                    <item name="email" xsi:type="string">MageKey\CustomerRestriction\Model\Restriction\Login\Email</item>
                </item>
            </argument>
        </arguments>
    </type>

</config>```

**Comment by magekey** [comment]
Pool DI has been moved to global scope in 2.1.4.
